version: "3.9"

services:
  backend:
    build: ./back
    ports:
      - 3000:3000
      - 5599:5599
    volumes:
      - ./back/src:/app/src
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  frontend:
    build: ./front
    ports:
      - 8000:8000
    volumes:
      - ./front/src:/app/src
#    environment:
#      - WDS_SOCKET_HOST=127.0.0.1
#      - CHOKIDAR_USEPOLLING=true
#      - WATCHPACK_POLLING=true